blog_show:
  pattern: /{slug}.html
  defaults: { _controller: SlyContentBundle:Blog:show }

blog_category:
  pattern: /{slug}
  defaults: { _controller: SlyContentBundle:Blog:categoryList }

blog:
  pattern: /
  defaults: { _controller: SlyContentBundle:Blog:list }