blog_admin:
  pattern: /blog
  defaults: { _controller: SlyContentBundle:Admin:blog }
  
snippet_admin:
  pattern: /snippets
  defaults: { _controller: SlyContentBundle:Admin:snippet }
  
tutorial_admin:
  pattern: /tutoriels
  defaults: { _controller: SlyContentBundle:Admin:tutorial }
  
watch_admin:
  pattern: /veille
  defaults: { _controller: SlyContentBundle:Admin:watch }