snippet_admin:
  pattern: /_admin
  defaults: { _controller: SlyContentBundle:Admin:snippet }

snippet_show:
  pattern: /{slug}.html
  defaults: { _controller: SlyContentBundle:Snippet:show }

snippet_category:
  pattern: /{slug}
  defaults: { _controller: SlyContentBundle:Snippet:categoryList }

snippet:
    pattern: /
    defaults: { _controller: SlyContentBundle:Snippet:list }