tutorial_admin:
  pattern: /_admin
  defaults: { _controller: SlyContentBundle:Admin:tutorial }

tutorial_feed:
    pattern: /feed.{_format}
    defaults: { _controller: SlyContentBundle:Tutorial:list }
    requirements:
      _format: xml

tutorial_show:
    pattern: /{slug}.html
    defaults: { _controller: SlyContentBundle:Tutorial:show }

tutorial_category:
    pattern: /{slug}
    defaults: { _controller: SlyContentBundle:Tutorial:listCategory }

tutorial:
    pattern: /
    defaults: { _controller: SlyContentBundle:Tutorial:list }