watch_admin:
  pattern: /_admin
  defaults: { _controller: SlyContentBundle:Admin:watch }

watch_feed:
    pattern: /feed.{_format}
    defaults: { _controller: SlyContentBundle:Watch:list }
    requirements:
      _format: xml

watch_category:
  pattern: /{slug}
  defaults: { _controller: SlyContentBundle:Watch:categoryList }

watch:
    pattern: /
    defaults: { _controller: SlyContentBundle:Watch:list }