blog_admin:
  pattern: /_admin
  defaults: { _controller: SlyContentBundle:Admin:blog }
  
blog_feed:
    pattern: /feed.{_format}
    defaults: { _controller: SlyContentBundle:Blog:list }
    requirements:
      _format: xml

blog_show:
  pattern: /{slug}.html
  defaults: { _controller: SlyContentBundle:Blog:show }

blog_category:
  pattern: /{slug}
  defaults: { _controller: SlyContentBundle:Blog:categoryList }

blog:
  pattern: /
  defaults: { _controller: SlyContentBundle:Blog:list }