tutorial_show:
    pattern: /{slug}.html
    defaults: { _controller: SlyContentBundle:Tutorial:show }

tutorial_category:
    pattern: /{slug}
    defaults: { _controller: SlyContentBundle:Tutorial:categoryList }

tutorial:
    pattern: /
    defaults: { _controller: SlyContentBundle:Tutorial:list }