parameters:
  sly.content.disqus:
    username: %disqus_username%
  
  sly.content.blog.maxperpage: 20
  sly.content.blog.otheritems.number: 5
  sly.content.watch.maxperpage: 30
  sly.content.watch.feedtitleskel: '__TITLE__ __MINILINK__ #veille __HASHTAGS__'
  sly.content.tutorial.maxperpage: 10
  sly.content.tutorial.dmplayer:
    width: 620
    height: 340
  sly.content.snippet.maxperpage: 30

services:
  twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
          - { name: twig.extension }
