parameters:
  sly.content.blog.maxperpage: 10
  sly.content.watch.maxperpage: 30
  sly.content.watch.feedtitleskel: '__TITLE__ __MINILINK__ #veille __HASHTAGS__'
  sly.content.tutorial.maxperpage: 10
  sly.content.tutorial.dmplayer:
    width: 620
    height: 340

services:
  twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
          - { name: twig.extension }
