imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    charset: UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating:
      engines: ['twig']
      assets_version: 1609201103
      assets_base_urls:
        http: [%cdn_main%]
        ssl: [%cdn_main_https%]
    session:
        default_locale: %locale%
        auto_start: true

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      project:
        name: %project_name%
        url: %project_url%
        simpleurl: %project_simpleurl%
        email: %project_email%
        shortemail: %project_shortemail%
        github:
          sources: %project_github_sources%
        google:
          analytics:
            id: %project_google_analytics_id%
      networks:
        rss: %networks_rss%
        twitter:
          url: %networks_twitter_url%
          username: %networks_twitter_username%
        facebook:
          url: %networks_facebook_url%
          username: %networks_facebook_username%
        linkedin: %networks_linkedin%
        googleplus: %networks_googleplus%
        flickr: %networks_flickr%
        foursquare: %networks_foursquare%

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        # jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        # jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%

jms_security_extra:
    secure_controllers: true
    secure_all_services: false

# Stof Doctrine extensions Configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true

# Avalanche twig filters Configuration
avalanche_imagine:
    filters:
        thumbnail:
            type: thumbnail
            options: { size: [80, 80], mode: inset }
        medium:
            type: thumbnail
            options: { size: [300, 300], mode: inset }
        tutorial:
            type: thumbnail
            options: { size: [320, 240], mode: inset }
        homeslider:
            type: thumbnail
            options: { size: [500, 250], mode: outbound }
