imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi: ~
    default_locale: %locale%
    translator: { fallback: %locale% }
    secret: %secret%
    charset: UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating:
      engines: ['twig']
      assets_version: 2011111901
      assets_version_format: %%s?v=%%s
      assets_base_urls:
        http: [%cdn_main%]
        ssl: [%cdn_main_https%]
    session:
        auto_start: true

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      project:
        name: %project_name%
        url: %project_url%
        simpleurl: %project_simpleurl%
        email: %project_email%
        shortemail: %project_shortemail%
        github:
          sources:
            url: %project_github_sources_url%
        google:
          analytics:
            id: %project_google_analytics_id%
        author:
          name: %project_author_name%
          email: %project_author_email%
      networks:
        rss: %networks_rss%
        twitter:
          url: %networks_twitter_url%
          username: %networks_twitter_username%
        facebook:
          url: %networks_facebook_url%
          username: %networks_facebook_username%
        linkedin: %networks_linkedin%
        googleplus: %networks_googleplus%
        flickr: %networks_flickr%
        github: %networks_github%
        githubp: %networks_githubp%
        foursquare: %networks_foursquare%
        facebookp: %networks_facebookp%
        googleplusp: %networks_googleplusp%
        viadeo: %networks_viadeo%
        flickr: %networks_flickr%

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
          jar: /usr/share/yui-compressor/yui-compressor.jar
        yui_js:
          jar: /usr/share/yui-compressor/yui-compressor.jar
        # closure:
        # jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        # jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%

jms_security_extra:
    secure_controllers: true
    secure_all_services: false

# Stof Doctrine extensions Configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true

# Avalanche twig filters Configuration
avalanche_imagine:
    filters:
        thumbnail:
            type: thumbnail
            options: { size: [110, 110], mode: outbound }
        lsThumbnail:
            type: thumbnail
            options: { size: [300, 120], mode: outbound }
        tutorial:
            type: thumbnail
            options: { size: [300, 200], mode: outbound }
        show:
            type: thumbnail
            options: { size: [620, 180], mode: outbound }
        portfolio:
            type: thumbnail
            options: { size: [660, 110], mode: outbound }
