imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      project:
        name: Slynett Labs
        url: http://www.slynett.com
        simpleurl: www.slynett.com
        email: hello@slynett.com
      networks:
        rss: http://feeds.feedburner.com/slynett
        twitter:
          url: http://twitter.com/Ph3nol
          username: Ph3nol
        facebook:
          url: http://facebook.com/slynett
          username: slynett
        linkedin: http://www.linkedin.com/cedric.dugat
        googleplus: http://goog.la/ph3

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Stof Doctrine extensions Configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true

# Avalanche twig filters Configuration            
avalanche_imagine:
    filters:
        thumbnail:
            type: thumbnail
            options: { size: [80, 80], mode: outbound }
        item:
            type: thumbnail
            options: { size: [220, 150], mode: outbound }
        medium:
            type: thumbnail
            options: { size: [400, 200], mode: outbound }