_imagine:
    resource: .
    type: imagine

_content:
    resource: "@SlyContentBundle/Resources/config/routing.yml"
    prefix: /

_core:
    resource: "@SlyCoreBundle/Resources/config/routing.yml"
    prefix: /
