security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        in_memory:
            memory:
                users:
                    user: { password: %admin_pass%, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/_admin/*
            anonymous: ~
            http_basic:
                realm: "Admin - Restricted access"

    access_control:
        - { path: ^/_admin/*, roles: ROLE_ADMIN }
