security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Admin - Restricted access"

    access_control:
        - { path: ^/_admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    ph3: { password: %admin_pass%, roles: [ 'ROLE_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext