parameters:
  sly.core.class: Sly\CoreBundle\Core
  sly.core.slyextension.class: Sly\CoreBundle\Extension\SlyExtension
  
  sly.core.lastcontent.number: 30

services:
  sly.core:
    class: %sly.core.class%
    arguments: [@service_container]
  twig.extension.sly:
      class: %sly.core.slyextension.class%
      tags:
          - { name: twig.extension }
